### ISSUE TITLE
possible to limit this to

### ISSUE THREAD

**Issue by hiqsociety** [plar/go-adaptive-radix-tree#21]
1. possible to make this into an lru cache with fixed size? so that it can automatically remove items based on fifo

2. how does this compare with patricia trie?
https://github.com/tchap/go-patricia
any benchmarks on speed and mem storage size used against patricia?

great work by the way

**Comment by plar** [comment]
1. it is possible, but it is outside the scope of this project. 
2. This library provides an implementation of the Adaptive Radix Tree (ART). ATR introduces the ability to update the data structure used for each internal node depending on how many children the node actually has. For more details see https://db.in.tum.de/~leis/papers/ART.pdf

I believe that ART should show better results in comparison with go-patricia. You can provide PR and prove otherwise :)

**Comment by hiqsociety** [comment]
it's kind of slow for in memory data structure.

do u intend to speed it up? it's like 1000x slower than what i expect it to be based on what golang can do

**Comment by prologic** [comment]
> it's kind of slow for in memory data structure.
> 
> 
> 
> do u intend to speed it up? it's like 1000x slower than what i expect it to be based on what golang can do

Where is your evidence for this?￼

**Comment by plar** [comment]
Please provide any code with benchmarks and more context and we will see what you compare and probably I would try to explain why it is slow.

**Comment by prologic** [comment]
I use this very library in an embedded k/v database similar in nature to BoltDB, BuntDB, RocksDB, etc called [Bitcask](https://git.mills.io/prologic/bitcask) (_benchmarks on the README on a shitty underpowered Macbook Air_) and benchmark code in the test suite.

I do not find it slow at all!

**Comment by prologic** [comment]
Example:

```#!sh
$ go test -v -run=BenchmarkScan -benchmem -bench=BenchmarkScan .
goos: darwin
goarch: amd64
pkg: git.mills.io/prologic/bitcask
cpu: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
BenchmarkScan
BenchmarkScan-12    	  697936	      1660 ns/op	     344 B/op	      33 allocs/op
PASS
ok  	git.mills.io/prologic/bitcask	2.252s
```
